<a href="https://colab.research.google.com/github/sayansen2003/sayansen2003/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [22]:
df = sns.load_dataset("titanic")

In [23]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [25]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [26]:
df.describe(include='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# Checking for missing values
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

# Handling missing values
# For simplicity, we will drop rows with missing values in 'embarked'
df.dropna(subset=['embarked'], inplace=True)

# Fill missing values in 'age' with the median age
df['age'].fillna(df['age'].median(), inplace=True)

# Drop the 'deck' column due to a large number of missing values
df.drop(columns=['deck'], inplace=True)

# Drop the 'embark_town' column as 'embarked' is more useful
df.drop(columns=['embark_town'], inplace=True)

# Drop 'alive' column as it is redundant with 'survived'
df.drop(columns=['alive'], inplace=True)

In [28]:
# One-hot encode categorical variables
df = pd.get_dummies(df, columns=['sex', 'embarked', 'class', 'who', 'adult_male', 'alone'], drop_first=True)

df.head()

,survived,pclass,age,sibsp,parch,fare,sex_male,embarked_Q,embarked_S,class_Second,class_Third,who_man,who_woman,adult_male_True,alone_True
0,0,3,22.0,1,0,7.2500,True,False,True,False,True,True,False,True,False
1,1,1,38.0,1,0,71.2833,False,False,False,False,False,False,True,False,False
2,1,3,26.0,0,0,7.9250,False,False,True,False,True,False,True,False,True
3,1,1,35.0,1,0,53.1000,False,False,True,False,False,False,True,False,False
4,0,3,35.0,0,0,8.0500,True,False,True,False,True,True,False,True,True

In [29]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the scaler
scaler = MinMaxScaler()

# Normalize numerical columns: 'age', 'fare'
df[['age', 'fare']] = scaler.fit_transform(df[['age', 'fare']])

df.head()

,survived,pclass,age,sibsp,parch,fare,sex_male,embarked_Q,embarked_S,class_Second,class_Third,who_man,who_woman,adult_male_True,alone_True
0,0,3,0.271174,1,0,0.014151,True,False,True,False,True,True,False,True,False
1,1,1,0.472229,1,0,0.139136,False,False,False,False,False,False,True,False,False
2,1,3,0.321438,0,0,0.015469,False,False,True,False,True,False,True,False,True
3,1,1,0.434531,1,0,0.103644,False,False,True,False,False,False,True,False,False
4,0,3,0.434531,0,0,0.015713,True,False,True,False,True,True,False,True,True

In [30]:
# Feature: Family size
df['family_size'] = df['sibsp'] + df['parch'] + 1

# Drop 'sibsp' and 'parch' as they are now redundant
df.drop(columns=['sibsp', 'parch'], inplace=True)

df.head()

,survived,pclass,age,fare,sex_male,embarked_Q,embarked_S,class_Second,class_Third,who_man,who_woman,adult_male_True,alone_True,family_size
0,0,3,0.271174,0.014151,True,False,True,False,True,True,False,True,False,2
1,1,1,0.472229,0.139136,False,False,False,False,False,False,True,False,False,2
2,1,3,0.321438,0.015469,False,False,True,False,True,False,True,False,True,1
3,1,1,0.434531,0.103644,False,False,True,False,False,False,True,False,False,2
4,0,3,0.434531,0.015713,True,False,True,False,True,True,False,True,True,1

In [31]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   survived         889 non-null    int64
 1   pclass           889 non-null    int64
 2   age              889 non-null    float64
 3   fare             889 non-null    float64
 4   sex_male         889 non-null    bool
 5   embarked_Q       889 non-null    bool
 6   embarked_S       889 non-null    bool
 7   class_Second     889 non-null    bool
 8   class_Third      889 non-null    bool
 9   who_man          889 non-null    bool
 10  who_woman        889 non-null    bool
 11  adult_male_True  889 non-null    bool
 12  alone_True       889 non-null    bool
 13  family_size      889 non-null    int64
dtypes: bool(9), float64(2), int64(3)
memory usage: 49.5 KB

,survived,pclass,age,fare,sex_male,embarked_Q,embarked_S,class_Second,class_Third,who_man,who_woman,adult_male_True,alone_True,family_size
0,0,3,0.271174,0.014151,True,False,True,False,True,True,False,True,False,2
1,1,1,0.472229,0.139136,False,False,False,False,False,False,True,False,False,2
2,1,3,0.321438,0.015469,False,False,True,False,True,False,True,False,True,1
3,1,1,0.434531,0.103644,False,False,True,False,False,False,True,False,False,2
4,0,3,0.434531,0.015713,True,False,True,False,True,True,False,True,True,1